group: deprecated-2017Q2
dist: trusty
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11
matrix:
  include:
    - name: "camunda 7.6.0 JDK 8"
      camunda_bpm_version: 7.6.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.3.1
      camunda_connect_version: 1.0.4
    - name: "camunda 7.6.0 JDK 11"
      camunda_bpm_version: 7.6.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.3.1
      camunda_connect_version: 1.0.4
      jdk: openjdk11
    - name: "camunda 7.7.0 JDK 8"
      camunda_bpm_version: 7.7.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.3.1
      camunda_connect_version: 1.0.4
      jdk: openjdk8
    - name: "camunda 7.7.0 JDK 11"
      camunda_bpm_version: 7.7.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.3.1
      camunda_connect_version: 1.0.4
      jdk: openjdk11
    - name: "camunda 7.8.0 JDK 8"
      camunda_bpm_version: 7.8.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.4.1
      camunda_connect_version: 1.0.5
      jdk: openjdk8
    - name: "camunda 7.8.0 JDK 11"
      camunda_bpm_version: 7.8.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.4.1
      camunda_connect_version: 1.0.5
      jdk: openjdk11
    - name: "camunda 7.9.0 JDK 8"
      camunda_bpm_version: 7.9.0
      camunda_commons_version: 1.4.0
      camunda_spin_version: 1.4.1
      camunda_connect_version: 1.0.5
      jdk: openjdk8
    - name: "camunda 7.9.0 JDK 11"
      camunda_bpm_version: 7.9.0
      camunda_commons_version: 1.5.0
      camunda_spin_version: 1.5.1
      camunda_connect_version: 1.0.6
      jdk: openjdk11
script: mvn install
